######################################################################
# Automatically generated by qmake (2.01a) Thu May 12 00:00:51 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -g -Wall

# Input
HEADERS += load_window.h
SOURCES += load_window.cpp \
           main.cpp 
